# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e5185b9a46498ad36df0633e71536928a5b67dd224064beae75b03695339c82b00249a551a46eb117a53038515f4bb855c725384eeecfd5cb286eabad3a42af

test:
  secret_key_base: 397350c5b8f1af9c41f901aaf27f4353e134857f146ce9660c0bb698da74387609029e3116690d823c710ee60be904e66d679acf4dbfa5f284aeb6debdf013ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
